version: '3.3'

services:
 app:
  container_name: PYTHON-API-BACKEND
  build: .
  environment:
      MONGODB_DATABASE: Manuel
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  ports:
    - "5000:5000"
  volumes:
    - .:/var/www/app
  depends_on:
    - db
  networks:
   - frontend
   - backend
 db:
  image: mongo:4.0.8
  container_name: mongo
  restart: unless-stopped
  environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
  ports:
    - "27017:27017"
  volumes:
    - mongodbdata:/data/db
  networks:
    - backend
 webserver:
    build: nginx
    container_name: webserver
    ports:
      - "443:443"
    depends_on:
      - app
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local
