version: '3.3'
services:
 app:
  container_name: flask
  build: .
  environment:
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DATABASE=Sentiment
  ports:
    - "5000:5000"
  volumes:
    - .:/var/www/app
  depends_on:
    - mongodb
  networks:
    - frontend
    - backend
 mongodb:
  image: mongo
  container_name: mongodb
  restart: unless-stopped
  command: ["sh", "-c", "mongosh mongodb://root:pwd@mongodb:27017/admin --eval load /docker-entrypoint-initdb.d/init-db.js"]
  environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=Sentiment
  ports:
    - "27017:27017"
  volumes:
    - mongodbdata:/data/db
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
  networks:
    - backend
 webserver:
    build: nginx
    container_name: SERVER
    ports:
      - "443:443"
    depends_on:
      - app
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
     - frontend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local